name: Build HTML5

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: "4.2.5"

      - name: Install Haxelib dependencies
        run: |
          haxelib setup ~/haxelib
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-addons
          haxelib install hscript
          haxelib install actuate
          haxelib install flixel-ui
          haxelib install faxe
          haxelib install hxvm-luajit
          haxelib install linc_luajit
          haxelib install extension-webview

      - name: Build HTML5
        run: |
          haxelib run lime test html5 -release

      - name: Upload HTML5 build
        uses: actions/upload-artifact@v4
        with:
          name: Psych-Engine-HTML5
          path: export/
